### PR TITLE
upgrade dependencies to be ready for babel 7

### LINKED ISSUE #21: babel 7 support
babel 7 republished under different name.

### PR DESCRIPTION
**Pull request by axe312ger**
This upgrades the plugin to be ready for babel 7.

Fixes #21 

This branch is released on npm. Install via:

```
npm i -D @axe312/babel-plugin-inline-import@beta
```

### CODE REVIEW

**Comment by zvictor** [comment]
I added you as contributor of this repo. What is your npm username?

**Comment by axe312ger** [comment]
Ohh wow nice, thank you.

My npm username is https://www.npmjs.com/~axe312

**Comment by axe312ger** [comment]
We should make sure to release this as `v4.0.0` since its a breaking change!

**Comment by zvictor** [comment]
it sounds right. could you take care of publishing the new version for us? :)

**Comment by gnawf** [comment]
@zvictor @axe312ger can one of you publish 4.0.0 thanks

**Pull request merged**
